<a href="https://colab.research.google.com/github/andrejarenkow/Jornada-Academica-Bioinfo-2023/blob/main/sisagua_dados_abertos_amostras_vigilancia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install wget

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9676 sha256=69ed5e436e8f20edf96e8580f09550c29b4de028ee31d00aa5bba39ba6e7f364
  Stored in directory: /root/.cache/pip/wheels/04/5f/3e/46cc37c5d698415694d83f607f833f83f0149e49b3af9d0f38
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

In [ ]:
import pandas as pd
import warnings
import wget
import sys

In [ ]:
pd.options.display.max_columns = None

In [ ]:
#create this bar_progress method which is invoked automatically from wget
def bar_progress(current, total, width=80):
  progress_message = "Downloading: %d%% [%d / %d] MBs" % (current / total * 100, current/1000000, total/1000000)
  # Don't use print() as it will print in new line every time.
  sys.stdout.write("\r" + progress_message)
  sys.stdout.flush()

In [ ]:
dados_municipio = pd.DataFrame()
for i in [2018, 2019, 2020, 2021,2022]:
   print(i)
   url = 'https://sage.saude.gov.br/dados/sisagua/vigilancia_parametros_basicos_' + str(i)+'.zip'
   filename = wget.download(url, bar=bar_progress)
   dados_ano = pd.read_csv(filename,
                         compression='zip', encoding='latin1', sep=';')
   filtro = (dados_ano['UF']=='RS')
   dados_rs_municipio = dados_ano[filtro].reset_index(drop=True)
   dados_municipio = pd.concat([dados_municipio, dados_rs_municipio])
   print(str(i) + ' - finalizado!')

dados_municipio

#dados_municipio.to_excel('dados_vigilancia_parametros_basicos_municipio_2014_2021.xlsx', index=False)

2018
Downloading: 100% [240 / 240] MBs

<ipython-input-5-dd5b3158bca3>:6: DtypeWarning: Columns (10,11,12,14,16,28,29,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dados_ano = pd.read_csv(filename,

2018 - finalizado!
2019
Downloading: 97% [251 / 257] MBs

<ipython-input-5-dd5b3158bca3>:6: DtypeWarning: Columns (10,11,12,14,16,28,29,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dados_ano = pd.read_csv(filename,

2019 - finalizado!
2020
Downloading: 100% [224 / 224] MBs

<ipython-input-5-dd5b3158bca3>:6: DtypeWarning: Columns (10,11,12,14,16,28,29,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dados_ano = pd.read_csv(filename,

2020 - finalizado!
2021
Downloading: 98% [260 / 263] MBs

<ipython-input-5-dd5b3158bca3>:6: DtypeWarning: Columns (10,11,12,14,16,28,29,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dados_ano = pd.read_csv(filename,

2021 - finalizado!
2022
Downloading: 100% [284 / 284] MBs

<ipython-input-5-dd5b3158bca3>:6: DtypeWarning: Columns (10,11,12,14,16,28,29,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dados_ano = pd.read_csv(filename,

2022 - finalizado!

,Região Geográfica,UF,Regional de Saúde,Município,Código IBGE,Número da amostra,Motivo da coleta,Tipo da Forma de Abastecimento,Código Forma de abastecimento,Nome da Forma de Abastecimento,Tipo da Instituição,Sigla da Instituição,Nome da Instituição,CNPJ da Instituição,Nome do escritório regional/local,CNPJ do escritório regional/local,Nome da ETA/UTA,Ano,Mês,Data da Coleta,Data do Laudo,Data de Registro no SISAGUA,Procedência da Coleta,Ponto de Coleta,Descrição do Local,Zona,Categoria Área,Área,Tipo do local,Local,Latitude,Longitude,Parâmetro (parâmetros básicos),Análise realizada,Resultado,Providência
0,SUL,RS,18ª CRS,TORRES,432150,181817000169,Rotina,SAA,S432150000002,TORRES,Empresa Estadual,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,9.280278e+13,SUPERINTENDENCIA REGIONAL LITORAL SURLIT,9.280278e+13,NaN,2018,7,2018/07/30 00:00:00.000,2018/07/31 00:00:00.000,2018/08/02 10:22:13.000,INTRA-DOMICILIAR / INTRA-PREDIAL,Torneira após a reservação,RUA SANTA MARIA 1005,Urbana,Bairro,SAO JORGE,NaN,NaN,NaN,NaN,Fluoreto (mg/L),NaN,"0,4",NaN
1,SUL,RS,5ª CRS,NOVA PRATA,431330,183532000057,Rotina,SAA,S431330000001,NOVA PRATA,Empresa Estadual,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,9.280278e+13,SUPERINTENDENCIA REGIONAL NORDESTE SURNE,9.280278e+13,NaN,2018,6,2018/06/19 00:00:00.000,2018/06/26 00:00:00.000,2018/07/09 15:59:44.000,INTRA-DOMICILIAR / INTRA-PREDIAL,Torneira após a reservação,AVENIDA CONEGO PERES,Urbana,Bairro,CENTRO,NaN,NaN,NaN,NaN,Fluoreto (mg/L),NaN,"0,5",NaN
2,SUL,RS,11ª CRS,GETULIO VARGAS,430890,09/2018,Rotina,SAA,S430890000001,GETÚLIO VARGAS,Empresa Estadual,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,9.280278e+13,SUPERINTENDENCIA REGIONAL PLANALTO SURPLA,9.280278e+13,NaN,2018,2,2018/02/26 00:00:00.000,2018/03/01 00:00:00.000,2018/03/28 15:57:53.000,SISTEMA DE DISTRIBUIÇÃO,Torneira antes da reservação,RUA: LUÍS BERGAMINI,Urbana,Bairro,CENTRO,NaN,NaN,"-27,88471","-52,23739",Cloro residual livre (mg/L),EM_CAMPO,"0,33",NaN
3,SUL,RS,1ª CRS,SAPUCAIA DO SUL,432000,183236000165,Rotina,SAA,S430770000001,ESTEIO,Empresa Estadual,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,9.280278e+13,SUPERINTENDENCIA REGIONAL SINOS SURSIN,9.280278e+13,NaN,2018,9,2018/09/05 00:00:00.000,2018/09/17 00:00:00.000,2018/12/03 10:15:05.000,SISTEMA DE DISTRIBUIÇÃO,Torneira antes da reservação,LAURENTINO JULIANO 237,Urbana,Bairro,PARAISO,NaN,NaN,NaN,NaN,Cloro residual livre (mg/L),EM_CAMPO,"2,24",NaN
4,SUL,RS,1ª CRS,TRIUNFO,432200,183239000121,Rotina,SAA,S432200000001,TRIUNFO,Empresa Estadual,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,9.280278e+13,SUPERINTENDENCIA REGIONAL METROPOLITANA SURMET,9.280278e+13,NaN,2018,9,2018/09/12 00:00:00.000,2018/09/18 00:00:00.000,2019/01/22 09:44:04.000,INTRA-DOMICILIAR / INTRA-PREDIAL,Torneira após a reservação,AV LUIS BARRETO,Urbana,Bairro,CENTRO,Estabelecimento de saúde,SECRETARIA MUNICIPAL DE SAUDE,NaN,NaN,Fluoreto (mg/L),NaN,"1,1",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238697,SUL,RS,10ª CRS,SAO GABRIEL,431830,224010000017,Rotina,SAI,I431830000004,TIARAJU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,2,2022/02/02 00:00:00.000,2022/02/03 00:00:00.000,2022/02/15 10:14:30.000,INTRA-DOMICILIAR / INTRA-PREDIAL,Torneira após a reservação,BR 290 KM 422,Rural,Povoado/Lugarejo,TIARAJU,NaN,NaN,NaN,NaN,Escherichia coli,NaN,AUSENTE,NaN
238698,SUL,RS,1ª CRS,SENTINELA DO SUL,432035,223122000114,Rotina,SAI,I432035000012,CERRO CHATO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,12,2022/12/14 00:00:00.000,2022/12/21 00:00:00.000,2022/12/28 09:07:51.000,SOLUÇÃO ALTERNATIVA,NaN,EST GARAMBEU,Rural,Povoado/Lugarejo,CERRO CHATO,NaN,NaN,NaN,NaN,Coliformes totais,NaN,PRESENTE,NaN
238699,SUL,RS,1ª CRS,BARAO DO TRIUNFO,430175,223104000062,Rotina,SAI,I430175000078,CERRO DOS ABREUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,8,2022/08/25 00:00:00.000,2022/08/30 00:00:00.000,2022/09/14 16:36:08.000,INTRA-DOMICILIAR / INTRA-PREDIAL,Torneira após a reservação,CERRO DOS ABREUS ASSOCIAÇAO DATA DOS AMADOR,Rural,Povoado/Lugarejo,INTERIOR,NaN,NaN,NaN,NaN,Escherichia coli,NaN,AUSENTE,NaN
238700,SUL,RS,1ª CRS,SENTINELA DO SUL,432035,223122000111,Rotina,SAI,I432035000002,ALTO DE DORES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,12,2022/12/14 00:00:00.000,2022/12/21 00:00:00.000,2022/12/28 09:06:09.000,SOLUÇÃO ALTERNATIVA,NaN,EST ALTO DE DORES,Rural,Povoado/Lugarejo,ALTO DE DORES,NaN,NaN,NaN,NaN,Coliformes totais,NaN,PRESENTE,NaN
238701,SUL,RS,1ª CRS,ELDORADO DO SUL,430676,223113000024,Rotina,SAI,I430676000015,PARQUE DAS ACACIAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,2,2022/02/10 00:00:00.000,2022/02/15 00:00:00.000,2022/02/16 15:39:17.000,INTRA-DOMICILIAR / INTRA-PREDIAL,Torneira após a reservação,AV SESMARIAS DOS FARRAPOS 2304,Urbana,Área urbana isolada,PARQUE ELDORADO,NaN,NaN,NaN,NaN,Escherichia coli,NaN,AUSENTE,NaN

In [ ]:
dados_municipio['Parâmetro (parâmetros básicos)'].unique()

array(['Fluoreto (mg/L)', 'Cloro residual livre (mg/L)', 'Turbidez (uT)',
       'pH', 'Bactérias Heterotróficas', 'Coliformes totais',
       'Escherichia coli', 'Cor Aparente (uH)',
       'Cloro residual combinado (mg/L)', 'Dióxido de Cloro (mg/L)'],
      dtype=object)

In [ ]:
colunas_manter = ['Regional de Saúde', 'Município',
       'Código IBGE','Código Forma de abastecimento',
       'Tipo da Forma de Abastecimento',
       'Nome da Forma de Abastecimento',
       'Sigla da Instituição', 'Nome da Instituição', 'Ano', 'Mês',
       'Data da Coleta','Parâmetro (parâmetros básicos)',
       'Resultado']

analises_manter = ['Fluoreto (mg/L)', 'Turbidez (uT)', 'Cloro residual livre (mg/L)',
       'Escherichia coli', ]

dados_municipio_limpo = dados_municipio[dados_municipio['Parâmetro (parâmetros básicos)'].isin(analises_manter)][colunas_manter]
dados_municipio_limpo.reset_index(drop=True, inplace=True)

In [ ]:
analises_manter = ['Fluoreto (mg/L)', 'Turbidez (uT)', 'Cloro residual livre (mg/L)',
       'Coliformes totais', 'Escherichia coli', ]

dados_fluoreto = dados_municipio_limpo[dados_municipio_limpo['Parâmetro (parâmetros básicos)']=='Fluoreto (mg/L)'].reset_index(drop=True)
dados_turbidez = dados_municipio_limpo[dados_municipio_limpo['Parâmetro (parâmetros básicos)']=='Turbidez (uT)'].reset_index(drop=True)
dados_cloro = dados_municipio_limpo[dados_municipio_limpo['Parâmetro (parâmetros básicos)']=='Cloro residual livre (mg/L)'].reset_index(drop=True)
dados_ecoli = dados_municipio_limpo[dados_municipio_limpo['Parâmetro (parâmetros básicos)']=='Escherichia coli'].reset_index(drop=True)

dados_fluoreto['Resultado'] = pd.to_numeric(dados_fluoreto['Resultado'].str.replace(',','.'))
dados_fluoreto['analise'] = ['Satisfatório'  if i <= 1.5 else 'Insatisfatório' for i in dados_fluoreto['Resultado']]

dados_turbidez['Resultado'] = pd.to_numeric(dados_turbidez['Resultado'].str.replace(',','.'))
dados_turbidez['analise'] = ['Satisfatório'  if i <= 5 else 'Insatisfatório' for i in dados_turbidez['Resultado']]

dados_cloro['Resultado'] = pd.to_numeric(dados_cloro['Resultado'].str.replace(',','.'))

analise = []
for i in dados_cloro['Resultado']:
  if i < 0.2:
    analise.append('Insatisfatório')

  elif i > 5:
    analise.append('Insatisfatório')

  else:
    analise.append('Satisfatório')

dados_cloro['analise'] = analise

dados_ecoli['analise'] = ['Satisfatório' if i == 'AUSENTE' else 'Insatisfatório' for i in dados_ecoli['Resultado']]

dados_2022 = pd.concat([dados_fluoreto, dados_turbidez, dados_cloro, dados_ecoli])
dados_2022.to_csv('dados_2022.csv', sep=';', index=False)

In [ ]:
dados_sac_ecoli = dados_2022[(dados_2022['Parâmetro (parâmetros básicos)']=='Escherichia coli')&(dados_2022['Tipo da Forma de Abastecimento']=='SAC')]
dados_sac_ecoli['chave'] = dados_sac_ecoli['Código Forma de abastecimento']+dados_sac_ecoli['Ano'].astype(str)
dados_sac_ecoli

<ipython-input-9-193867ff1954>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_sac_ecoli['chave'] = dados_sac_ecoli['Código Forma de abastecimento']+dados_sac_ecoli['Ano'].astype(str)

,Regional de Saúde,Município,Código IBGE,Código Forma de abastecimento,Tipo da Forma de Abastecimento,Nome da Forma de Abastecimento,Sigla da Instituição,Nome da Instituição,Ano,Mês,Data da Coleta,Parâmetro (parâmetros básicos),Resultado,analise,chave
119,1ª CRS,CAMAQUA,430350,C430350000011,SAC,ESCOLA MUNICIPAL RUI BARBOSA,KF,KF SOLUCOES AMBIENTAIS LTDA,2018,3,2018/03/21 00:00:00.000,Escherichia coli,PRESENTE,Insatisfatório,C4303500000112018
261,1ª CRS,CAMAQUA,430350,C430350000020,SAC,ESCOLA MUNICIPAL 15 DE NOVEMBRO,KF,KF SOLUCOES AMBIENTAIS LTDA,2018,11,2018/11/06 00:00:00.000,Escherichia coli,PRESENTE,Insatisfatório,C4303500000202018
791,1ª CRS,VIAMAO,432300,C432300000025,SAC,CAMINHÃO TANQUE SME,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,2018,10,2018/10/16 00:00:00.000,Escherichia coli,AUSENTE,Satisfatório,C4323000000252018
969,1ª CRS,CAMAQUA,430350,C430350000010,SAC,ESCOLA MUNICIPAL SANTO ANTÔNIO,KF,KF SOLUCOES AMBIENTAIS LTDA,2018,4,2018/04/11 00:00:00.000,Escherichia coli,AUSENTE,Satisfatório,C4303500000102018
1415,1ª CRS,ELDORADO DO SUL,430676,C430676000016,SAC,CORSAN - ROSELI CORREA,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,2018,11,2018/11/22 00:00:00.000,Escherichia coli,PRESENTE,Insatisfatório,C4306760000162018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268323,4ª CRS,TOROPI,432149,C432149000011,SAC,SANTO INACIO,NaN,NaN,2022,12,2022/12/21 00:00:00.000,Escherichia coli,AUSENTE,Satisfatório,C4321490000112022
268324,4ª CRS,FORMIGUEIRO,430840,C430840000004,SAC,CERRO DO LORO,NaN,NaN,2022,11,2022/11/22 00:00:00.000,Escherichia coli,PRESENTE,Insatisfatório,C4308400000042022
268325,1ª CRS,GUAIBA,430930,C430930000022,SAC,CASA AILTON VERA,NaN,NaN,2022,10,2022/10/19 00:00:00.000,Escherichia coli,PRESENTE,Insatisfatório,C4309300000222022
268326,3ª CRS,JAGUARAO,431100,C431100000002,SAC,MULTILOG LOGISTICA SUL LTDA,NaN,NaN,2022,1,2022/01/11 00:00:00.000,Escherichia coli,AUSENTE,Satisfatório,C4311000000022022
268327,2ª CRS,RODEIO BONITO,431590,C431590000011,SAC,LINHA SANTA ANA,NaN,NaN,2022,11,2022/11/29 00:00:00.000,Escherichia coli,AUSENTE,Satisfatório,C4315900000112022

In [ ]:
pd.pivot_table(dados_municipio, index='Mês',columns='Ano', values='Município', aggfunc='count')

Ano   2018   2019   2020   2021   2022
Mês
1    18725  19051  17734  18034  18908
2    18889  19641  17989  18808  19832
3    20956  20620  20215  20566  20969
4    21783  21022  19487  21081  20095
5    21989  20802  22145  21810  21536
6    20424  21716  21958  20700  19729
7    21425  21923  22592  21012  20712
8    22567  21996  22300  21759  21587
9    20264  21116  20967  20317  19380
10   22373  20590  21147  21129  20076
11   21938  22036  21327  22527  19923
12   18805  16106  18583  18827  15955

In [ ]:
dados_fluoreto

analise = []
for resul,tipo in zip(dados_fluoreto['Resultado'],dados_fluoreto['Tipo da Forma de Abastecimento'] ):
  if tipo == 'SAA':
    if resul<=0.9 and resul >=0.6:
      analise.append('Satisfatório')
    else:
      analise.append('Insatisfatório')

  else:
    if resul<=1.5:
      analise.append('Satisfatório')
    else:
      analise.append('Insatisfatório')

dados_fluoreto['Analise_detalhe'] = analise

dados_fluoreto

,Regional de Saúde,Município,Código IBGE,Código Forma de abastecimento,Tipo da Forma de Abastecimento,Nome da Forma de Abastecimento,Sigla da Instituição,Nome da Instituição,Ano,Mês,Data da Coleta,Parâmetro (parâmetros básicos),Resultado,analise,Analise_detalhe
0,18ª CRS,TORRES,432150,S432150000002,SAA,TORRES,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,2018,7,2018/07/30 00:00:00.000,Fluoreto (mg/L),0.40,Satisfatório,Insatisfatório
1,5ª CRS,NOVA PRATA,431330,S431330000001,SAA,NOVA PRATA,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,2018,6,2018/06/19 00:00:00.000,Fluoreto (mg/L),0.50,Satisfatório,Insatisfatório
2,1ª CRS,TRIUNFO,432200,S432200000001,SAA,TRIUNFO,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,2018,9,2018/09/12 00:00:00.000,Fluoreto (mg/L),1.10,Satisfatório,Insatisfatório
3,14ª CRS,SANTA ROSA,431720,S431720000001,SAA,SANTA ROSA,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,2018,3,2018/03/05 00:00:00.000,Fluoreto (mg/L),0.60,Satisfatório,Satisfatório
4,1ª CRS,IGREJINHA,431010,S431010000001,SAA,IGREJINHA,CORSAN,COMPANHIA RIOGRANDENSE DE SANEAMENTO,2018,2,2018/02/19 00:00:00.000,Fluoreto (mg/L),0.40,Satisfatório,Insatisfatório
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217438,1ª CRS,NOVA HARTZ,431306,I431306000030,SAI,IMIGRANTE,NaN,NaN,2022,3,2022/03/16 00:00:00.000,Fluoreto (mg/L),0.10,Satisfatório,Satisfatório
217439,1ª CRS,NOVA HARTZ,431306,I431306000027,SAI,PRIMAVERA,NaN,NaN,2022,8,2022/08/11 00:00:00.000,Fluoreto (mg/L),0.90,Satisfatório,Satisfatório
217440,12ª CRS,SAO BORJA,431800,I431800000113,SAI,ROBSON GOMES,NaN,NaN,2022,11,2022/11/24 00:00:00.000,Fluoreto (mg/L),0.40,Satisfatório,Satisfatório
217441,6ª CRS,SAO JOAO DA URTIGA,431842,I431842000005,SAI,SAI SANTA BARBARA,NaN,NaN,2022,2,2022/02/22 00:00:00.000,Fluoreto (mg/L),0.08,Satisfatório,Satisfatório
217442,6ª CRS,BARROS CASSAL,430200,I430200000938,SAI,RES ANTONIA DARCI GARCIA,NaN,NaN,2022,4,2022/04/07 00:00:00.000,Fluoreto (mg/L),0.07,Satisfatório,Satisfatório

In [ ]:
dados_fluoreto_empilhado = pd.melt(((pd.crosstab(dados_fluoreto['Analise_detalhe'], dados_fluoreto['Ano'], normalize='columns')*100).round(2)).reset_index(),
                                   id_vars='Analise_detalhe', value_vars=[2018,2019,2020,2021,2022], value_name='Porcentagem')
dados_fluoreto_empilhado

  Analise_detalhe   Ano  Porcentagem
0  Insatisfatório  2018        22.34
1    Satisfatório  2018        77.66
2  Insatisfatório  2019        21.01
3    Satisfatório  2019        78.99
4  Insatisfatório  2020        21.00
5    Satisfatório  2020        79.00
6  Insatisfatório  2021        21.41
7    Satisfatório  2021        78.59
8  Insatisfatório  2022        19.68
9    Satisfatório  2022        80.32

In [ ]:
import plotly.express as px


fig = px.bar(dados_fluoreto_empilhado.sort_values('Analise_detalhe', ascending=False), x="Ano", y="Porcentagem", color="Analise_detalhe",
             text='Porcentagem', color_discrete_sequence=["lightgreen", "indianred"])
fig.show()